### PR TITLE
fix(firebase_database): Fix a null exception when using `runTransaction` with Maps.

### LINKED ISSUE #6002: 🐛 [realtime_database] nullable  type not handled properly  ( firebase_database: ^7.0.0-dev.1)
## Bug report

**Describe the bug**
Unhandled Exception: Null check operator used on a null value

### Error Log
Screenshot 2021-05-03 at 8 03 57 AM

**getting above error in line no:42**

### issue with code  ( line no:36 and line no: 42)
Screenshot 2021-05-03 at 8 05 14 AM

### PR DESCRIPTION
**Pull request by rrousselGit**
## Related Issues

fixes #6002

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_database/firebase_database/lib/src/database_reference.dart [hunk 1]
```diff
@@ -165,29 +165,27 @@ class DatabaseReference extends Query {
           map['error'] != null ? DatabaseError._(map['error']) : null;
       final bool committed = map['committed'];
       final DataSnapshot? dataSnapshot = map['snapshot'] != null
-          ? DataSnapshot._fromJson(map['snapshot'], map['childKeys'])
+          ? DataSnapshot._fromJson(map['snapshot'], null)
```
Comment (rrousselGit) [inline packages/firebase_database/firebase_database/lib/src/database_reference.dart:168]: Native never sends any `childKeys` parameters. So I just removed it

Comment (Salakar) [reply packages/firebase_database/firebase_database/lib/src/database_reference.dart:168]: Is this right? cc @russellwheatley since I think you added the `childKeys` thing right so could you confirm? Thanks!

Comment (rrousselGit) [reply packages/firebase_database/firebase_database/lib/src/database_reference.dart:168]: I looked at both the java and objective C code and didn't see a `childKeys`

Maybe it wasn't implemented for transactions.

Comment (russellwheatley) [reply packages/firebase_database/firebase_database/lib/src/database_reference.dart:168]: It's not used in transactions, but it is used in every event listener with a reference to the database.

[Here](https://github.com/FirebaseExtended/flutterfire/blob/2ca476431a2a8ed262080bf7282915a3b893f429/packages/firebase_database/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java#L211) is where `childKeys` is appended to the map passed back to Flutter.

[Here](https://github.com/FirebaseExtended/flutterfire/blob/2ca476431a2a8ed262080bf7282915a3b893f429/packages/firebase_database/firebase_database/android/src/main/java/io/flutter/plugins/firebase/database/MethodCallHandlerImpl.java#L236-L260) are all the event types that pass back `childKeys`.

[Here](https://github.com/FirebaseExtended/flutterfire/blob/2ca476431a2a8ed262080bf7282915a3b893f429/packages/firebase_database/firebase_database/lib/src/event.dart#L22) is where the event creates a `DataSnapshot` where `childKeys` is expected in the database package.

Comment (rrousselGit) [reply packages/firebase_database/firebase_database/lib/src/database_reference.dart:168]: So there are still cases where `runTransaction` can receive a `childKeys`?

Comment (russellwheatley) [reply packages/firebase_database/firebase_database/lib/src/database_reference.dart:168]: no, not `runTransaction` from what i can see. It is only for events.

**Review by Salakar — APPROVED** [review]
