### PR TITLE
fix(firebase_core, cloud_firestore): Fix FirebaseOptions hashCode

### LINKED ISSUE #3262: [firebase_core , cloud_firestore] hashCode of DocumentReference seems broken
**Describe the bug**

#2524 was closed by #2942, but added test cases don't partially cover intention of #2524.

In this senario,

```dart
DocumentReference docRef = firestore.collection('foo').doc('bar');
// Same firestore instance and same path
DocumentReference docRef2 = firestore.collection('foo').doc('bar');
```

With #2524 this succeeds, but currently it fails.

```dart
// Same instance
expect(docRef.hashCode == docRef.hashCode, isTrue);
// Different instance but same firestore instance and same path
expect(docRef.hashCode == docRef2.hashCode, isTrue);
```
**Expected behavior**

In the test case above, both of them should succeed.
I tried to fix at #3263.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 1.21.0-9.0.pre, on Mac OS X 10.15.6 19G73, locale en-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.48.0)
[✓] Connected device (6 available)
```

@Ehesp Could you consider this?

### PR DESCRIPTION
**Pull request by mono0926**
## Description

Fixes #3262

`hashCode` of same instance `FirebaseOptions` is changed every time you get because `asMap` returns new `Map`.
The problem is fixed by changing `hashObjects(asMap.entries)` to `asMap.toString().hashCode`.

`asMap.toString()` seems appropriate because `==` is implemented by using it. 

https://github.com/FirebaseExtended/flutterfire/blob/51b73e17f9a938e361e5db024c3886ffa82279c5/packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart#L217-L222

## Related Issues

- #3262

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] If the pull request affects only one plugin, the PR title starts with the name of the plugin in brackets (e.g. [cloud_firestore])
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [ ] I updated pubspec.yaml with an appropriate new version according to the [pub versioning philosophy].
- [ ] I updated CHANGELOG.md to add a description of the change.
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

**Comment by mono0926** [comment]
My main purpose is fixing #3262, so `cloud_firestore` is mixed.
Should I split it like this?

- First pull request(#3263): Only fix the `hashCode` bug of `firebase_core`
- Second pull request: after first pull request merged, add `cloud_firestore` tests

File: packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart [hunk 1]
```diff
@@ -223,7 +223,7 @@ class FirebaseOptions {
 
   @override
   int get hashCode {
-    return hashObjects(asMap.entries);
+    return asMap.toString().hashCode;
```
Comment (MrAlek) [inline packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart:226]: This is a pretty expensive operation, first converting the object to a map and then running `toString()`. The `hashCode` is supposed to be computed significantly faster than true equality.

It would be much faster to compute the hash manually by looking at the properties, like many of the built-in types in the Flutter framework.

```suggestion
    return hashValues(
      apiKey ?? googleAppID,
      appId,
      messagingSenderId ?? gcmSenderID,
      projectId ?? projectID,
      authDomain,
      databaseURL,
      storageBucket,
      measurementId,
      trackingId ?? trackingID,
      deepLinkURLScheme,
      androidClientId ?? clientID,
      iosClientId ?? clientID,
      iosBundleId ?? bundleID,
      appGroupId,
    );
```

Comment (mono0926) [reply packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart]: Thanks, I agree 👍

**Comment by MrAlek** [comment]
@googlebot I fixed it.

**Comment by mono0926** [comment]
@Salakar @Ehesp 

I think this bug is very serious.
Why don't you care about it for such a long time?

File: packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart [hunk 2]
```diff
@@ -223,7 +223,22 @@ class FirebaseOptions {
 
   @override
   int get hashCode {
-    return hashObjects(asMap.entries);
+    return hashValues(
+      apiKey ?? googleAppID,
```
Comment (Ehesp) [inline packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart:227]: THe `googleAppId` here should be on the line below?

**Review by Ehesp — CHANGES_REQUESTED** [review]

File: packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart (hunk 2 above)
Comment (mono0926) [reply packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart:227]: @Ehesp 

Is this exiting code also mistake?
If so, I'll correct both.
https://github.com/FirebaseExtended/flutterfire/blob/2273334b4d661850f5120b5b3c96bb617a964d05/packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart#L199

Comment (Ehesp) [reply packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart:227]: Hmm potentially yeah, I'll check it out.

Comment (MrAlek) [reply packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart:227]: According to the definition, the `googleAppID` is deprecated and replaced by `apiKey` which is why it's written this way.

https://github.com/FirebaseExtended/flutterfire/blob/2273334b4d661850f5120b5b3c96bb617a964d05/packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart#L52

Comment (MrAlek) [reply packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart:227]: Definitely seems like it, good catch.

https://github.com/FirebaseExtended/flutterfire/blob/2273334b4d661850f5120b5b3c96bb617a964d05/packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart#L80
https://github.com/FirebaseExtended/flutterfire/blob/2273334b4d661850f5120b5b3c96bb617a964d05/packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart#L81

Comment (Ehesp) [reply packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart:227]: Yah, could you fix that apart of this PR?

**Comment by MrAlek** [comment]
@googlebot I consent.

File: packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart (hunk 2 above)
Comment (mono0926) [reply packages/firebase_core/firebase_core_platform_interface/lib/src/firebase_options.dart]: @Ehesp 
Okay, I fixed them at https://github.com/FirebaseExtended/flutterfire/pull/3263/commits/def21881b36563598f40e6e509d5e89395c89e43 👍

**Comment by mono0926** [comment]
@googlebot I consent.

**Comment by mono0926** [comment]
@Ehesp 
What else needs to be done for this Pull Request to be merged?

> cla/google — CLAs are signed, but unable to verify author consent

Co-authored of https://github.com/FirebaseExtended/flutterfire/pull/3263/commits/f587e2b258541f1715210390d9ff46702500aa5e is `Alek Åström <alek.astrom@gmail.com>`, but the email address of @MrAlek is alek@iosnomad.com. Is this the reason for the failure to verify the author consent?

**Comment by AndroidNils** [comment]
@MrAlek Did you add all your email addresses to Google CLA?

image

https://cla.developers.google.com/clas

File: packages/firebase_core/firebase_core_platform_interface/test/firebase_options_test.dart [hunk 3]
```diff
@@ -23,6 +23,7 @@ void main() {
           projectId: 'projectId');
 
       expect(options1 == options2, isTrue);
+      expect(options1.hashCode == options2.hashCode, isTrue);
```
Comment (AndroidNils) [inline packages/firebase_core/firebase_core_platform_interface/test/firebase_options_test.dart:26]: What was the reason to change this to `.hashCode`?

Comment (mono0926) [reply packages/firebase_core/firebase_core_platform_interface/test/firebase_options_test.dart:26]: Not changed, but addded.
It failed before this PR because original implementation was broken.

Comment (AndroidNils) [reply packages/firebase_core/firebase_core_platform_interface/test/firebase_options_test.dart:26]: Oh, my issue! I did not look properly and thought that the line was replaced and not added. Everything fine 👌

**Comment by MrAlek** [comment]
@AndroidNils I've signed the CLA with both email accounts. According to the following info posted by @googlebot, a maintainer should be able to override by setting the `cla` label to `yes` on the PR.

> All (the pull request submitter and all commit authors) CLAs are signed, **but** one or more commits were authored or co-authored by someone other than the pull request submitter.
> 
> We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that by leaving a comment that contains only `@googlebot I consent.` in this pull request.
> 
> _Note to project maintainer:_ There may be cases where the author cannot leave a comment, or the comment is not properly detected as consent. In those cases, you can manually confirm consent of the commit author(s), and set the `cla` label to `yes` (if enabled on your project).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2FFirebaseExtended%2Fflutterfire%2Fpull%2F3263) for more info**.

**Comment by mono0926** [comment]
@Ehesp 

Could you clarify what blocks this from merging for so long time?

I re-run checks, and it contains some errors, but it seems not related to this change.

- https://github.com/FirebaseExtended/flutterfire/pull/3263/checks?check_run_id=1642033172
- https://github.com/FirebaseExtended/flutterfire/pull/3263/checks?check_run_id=1642033097

**Comment by MrAlek** [comment]
Another ping @Ehesp. Although the fix is simple & the bug subtle, it's very serious and might be causing all sorts of problems in apps out there.

**Comment by mono0926** [comment]
@Salakar 
 Could you clarify what blocks this from merging for so long time?

**Review by Ehesp — APPROVED** [review]

**Comment by rrousselGit** [comment]
@googlebot I consent.

File: packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml [hunk 4]
```diff
@@ -11,6 +11,7 @@ environment:
   flutter: '>=1.9.1+hotfix.5'
 
 dependencies:
+  collection: ^1.15.0
```
Comment (Salakar) [inline packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml:14]: IS this right, on the Analytics package?

Comment (rrousselGit) [reply packages/firebase_analytics/firebase_analytics_platform_interface/pubspec.yaml:14]: Oopsy

**Review by Salakar — APPROVED** [review]

**Comment by MrAlek** [comment]
Thanks for taking care of this @rrousselGit!
