### PR TITLE
fix(firebase_auth): Move communication to EventChannels

### LINKED ISSUE #3507: 🐛 [Cloud Firestore]  Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'void f.a.b.a.j.a(java.lang.String, java.lang.Object)' on a null object reference
## Bug report

These issues only happen on **Android phones** only. It worked fine in iOS. I'm using Flutter 1.20.3 and use cloud_firestore ^0.14.0+2

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void f.a.b.a.j.a(java.lang.String, java.lang.Object)' on a null object reference
io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.a (FlutterFirebaseFirestorePlugin.java:67)
io.flutter.plugins.firebase.firestore.-$$Lambda$FlutterFirebaseFirestorePlugin$Om-QqNeCto0p2tej6MhbBamtjUw.onEvent (-.java:6)
com.google.firebase.firestore.Query.a (Query.java:27)
com.google.firebase.firestore.Query$$Lambda$3.a (Query.java:6)
com.google.firebase.firestore.core.AsyncEventListener.a (AsyncEventListener.java:6)
com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run (AsyncEventListener.java:6)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:8125)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:496)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1100)
```

### LINKED ISSUE #4416: 🐛 [firebase_auth] NullPointerException when ID token changed but channel is gone
## Bug report

Crashlytics stack trace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object, io.flutter.plugin.common.MethodChannel$Result)' on a null object reference
       at io.flutter.plugins.firebase.auth.FlutterFirebaseAuthPlugin.lambda$null$1(FlutterFirebaseAuthPlugin.java:539)
       at io.flutter.plugins.firebase.auth.-$$Lambda$FlutterFirebaseAuthPlugin$SQAGnfsVv7byAY7rk65tey1yNTg.onIdTokenChanged(-.java:4)
       at com.google.firebase.auth.zzi.run(zzi.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage(zzj.java:6)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8154)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

Root cause: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java#L539

``` java
                  channel.invokeMethod(
                      "Auth#idTokenChanges",
                      event,
                      getMethodChannelResultHandler("Auth#idTokenChanges"));
```

### Steps to reproduce

Not sure for a real App, but we should be writing having a driver test for it.

My suggestion is to move ID token listener & auth state listener into a EventStream (same approach like #4209) and get rid of the issue from the ground up. I'm happy to work on a PR for this.

### PR DESCRIPTION
**Pull request by ened**
## Description

Similar to #4209, this PR addresses some issues rgd. isolate communication pertaining left-open "channels" to communicate back from native side to Dart.

Instead, the Flutter EventChannel mechanism is now used for the following parts:
 - ID Token Changes
 - Auth State changes
 - Phone Number verification

## Related Issues

Closes #3507
Closes #4416 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

# Please help testing the PR

Add the following to your `pubspec.yaml`:

``` yaml
dependency_overrides:
  firebase_auth:
    git:
      url: https://github.com/ened/flutterfire.git
      ref: fix/4416-firebase-auth
      path: packages/firebase_auth/firebase_auth
  firebase_auth_platform_interface:
    git:
      url: https://github.com/ened/flutterfire.git
      ref: fix/4416-firebase-auth
      path: packages/firebase_auth/firebase_auth_platform_interface
```

### CODE REVIEW

File: packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m [hunk 1]
```diff
@@ -131,20 +127,29 @@ - (void)cleanupWithCompletion:(void (^)(void))completion {
...
 }
 
 - (void)handleMethodCall:(FlutterMethodCall *)call result:(FlutterResult)flutterResult {
   FLTFirebaseMethodCallErrorBlock errorBlock =
       ^(NSString *_Nullable code, NSString *_Nullable message, NSDictionary *_Nullable details,
         NSError *_Nullable error) {
         if (code == nil) {
-          NSDictionary *errorDetails = [self getNSDictionaryFromNSError:error];
+          NSDictionary *errorDetails = [FLTFirebaseAuthPlugin getNSDictionaryFromNSError:error];
+          [self storeAuthCredentialIfPresent:error];
```
Comment (ened) [inline packages/firebase_auth/firebase_auth/ios/Classes/FLTFirebaseAuthPlugin.m:152]: This was extracted from `getNSDictionaryFromNSError` in order to make `getNSDictionaryFromNSError` static. 

I think the "getNSDictionaryFrom*" methods should live in a static utility class to enforce SRP.

**Comment by ened** [comment]
@rrousselGit @Salakar @Ehesp hi there - this PR is ready for review. 

The e2e example currently fails due to the phone number being linked with another account. The same error can be observed on the master branch.

Could you spare a minute to take a look?

File: packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart [hunk 2]
```diff
@@ -604,23 +527,60 @@ class MethodChannelFirebaseAuth extends FirebaseAuthPlatform {
...
+      });
     } catch (e) {
       throw convertPlatformException(e);
     }
   }
 }
+
+/// Simple helper class to make nullable values transferable through StreamControllers.
+class _ValueWrapper<T> {
+  _ValueWrapper(this.value);
```
Comment (rrousselGit) [inline packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart:581]:
```suggestion
  const _ValueWrapper(this.value);
```

File: packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart [hunk 3]
```diff
@@ -604,23 +527,60 @@ class MethodChannelFirebaseAuth extends FirebaseAuthPlatform {
...
         'autoRetrievedSmsCodeForTesting': autoRetrievedSmsCodeForTesting,
       });
+
+      EventChannel(eventChannelName!)
+          .receiveBroadcastStream()
+          .listen((arguments) {
+        final name = arguments['name'];
+        if (name == 'Auth#phoneVerificationCompleted') {
+          final int token = arguments['token'];
+          final String /*!*/ smsCode = arguments['smsCode'];
```
Comment (rrousselGit) [inline packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart:546]: auth is already null safe. There's no need for such comment

Does this implies that `token` and other variables **without** this comment should be nullable instead?
Due to implicit-cast being currently enable, that may be a source of a bug

File: packages/firebase_auth/firebase_auth/ios/Classes/FLTPhoneNumberVerificationStreamHandler.m [hunk 4]
```diff
@@ -0,0 +1,65 @@
...
+    }
+  };
+
+  // Try catch to capture 'missing URL scheme' error.
+  @try {
+    [[FIRPhoneAuthProvider providerWithAuth:_auth] verifyPhoneNumber:_phoneNumber
+                                                          UIDelegate:nil
+                                                          completion:completer];
+  } @catch (NSException *exception) {
+    NSLog(@"%@", exception);
```
Comment (russellwheatley) [inline packages/firebase_auth/firebase_auth/ios/Classes/FLTPhoneNumberVerificationStreamHandler.m:48]: Think we can remove this now.

**Review by russellwheatley — CHANGES_REQUESTED** [review]
A few nitpicks from me. One other thing would be to run `melos run format` from root as I think there is one iOS file that needs formatting. Other than that, great work again, @ened. We really appreciate it.

File: packages/firebase_auth/firebase_auth/ios/Classes/FLTAuthStateChannelStreamHandler.m [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+          });
+        }
+      }];
+
+  return nil;
+}
+
+- (FlutterError *)onCancelWithArguments:(id)arguments {
+  if (_listener) {
+    [_auth removeIDTokenDidChangeListener:_listener];
```
[the remark this answers is not in the document]
Comment (ened) [reply packages/firebase_auth/firebase_auth/ios/Classes/FLTAuthStateChannelStreamHandler.m:45]: thx!

File: packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java [hunk 6]
```diff
@@ -1377,9 +1216,9 @@ public void onMethodCall(@NonNull MethodCall call, @NonNull Result result) {
     return Tasks.call(
         cachedThreadPool,
         () -> {
-          removeEventListeners();
+          // TODO: not sure if this is applicable here.
+          //          removeEventListeners();
```
[the remark this answers is not in the document]
Comment (ened) [reply packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java:1220]: When does `didReinitializeFirebaseCore` get called usually?

File: packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart (hunk 3 above)
Comment (ened) [reply packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart:546]: `token` should be NOT nullable, `smsCode` may be null - just checked in the Android side. correction on the way.

File: packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (ened) [reply packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java:1220]: Ah, when the core is reinitialized (doh!) - in the firebase core plugin. If the user changes the firebase project then we need to clean up the plugins. There is a problem in `cloud_firestore` as well as this PR: The `didReinitializeFirebaseCore` does not clear the event listeners, which may cause errors. The listeners get cleared up when the plugin is destroyed. Hm.. 

Sounds like a central cleanup method in the plugin would be the right way to go here.

File: packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart [hunk 7]
```diff
@@ -604,23 +527,60 @@ class MethodChannelFirebaseAuth extends FirebaseAuthPlatform {
...
+          .invokeMethod<String>('Auth#verifyPhoneNumber', <String, dynamic>{
         'appName': app.name,
-        'handle': handle,
         'phoneNumber': phoneNumber,
         'timeout': timeout.inMilliseconds,
         'forceResendingToken': forceResendingToken,
         'autoRetrievedSmsCodeForTesting': autoRetrievedSmsCodeForTesting,
       });
+
+      EventChannel(eventChannelName!)
```
Comment (ened) [inline packages/firebase_auth/firebase_auth_platform_interface/lib/src/method_channel/method_channel_firebase_auth.dart:540]: This StreamSubscription is not cancelled.

**Comment by Salakar** [comment]
@googlebot I consent.

File: packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (Salakar) [reply packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java:1220]: `didReinitializeFirebaseCore` is also called on Dart Hot Restarts in dev (was mainly added for this purpose) - so it would be best if the event listeners are also cleaned up here otherwise these would linger in native when Dart is no longer aware of them?

**Comment by ened** [comment]
Thank you @Salakar for joining :)

**Comment by Salakar** [comment]
> Thank you @Salakar for joining :)

No worries, I think this is the last bit and then we're good to merge and ship;

image

**Comment by ened** [comment]
> > Thank you @Salakar for joining :)
> 
> No worries, I think this is the last bit and then we're good to merge and ship;
> 
> image
> 
> The test failures re `credential in use` are also occurring on master so unrelated to this PR and being investigated separately.

OK will take care. I did not see your reply before just now.

**Comment by ened** [comment]
@Salakar Addressed the last piece of feedback. Please also see #5852 for the similar fix in `cloud_firestore`.

**Review by Salakar — APPROVED** [review]
