### PR TITLE
fix(ios): don't replace `UNUserNotificationCenter` delegate when protocol conforms to `FlutterApplicationLifeCycleDelegate`

### LINKED ISSUE #4026: 🐛 [firebase_messaging 8.0.0-dev.5] App crashes when opening notification with data message in iOS
## Bug report

**Describe the bug**
I am sending a notification with this payload to the app.
```
payload = {
                        notification: {
                            title: `You have received a new message!`,
                            body: contentMessage,
                            badge: '1',
                            sound: 'default',
                            click_action: 'FLUTTER_NOTIFICATION_CLICK',
                            idFrom: idFrom,
                            idTo: idTo,
                        },
                        data: {
                                asking: 'true'
                                screen: 'active'
                                type: 'qna',
                                convoId: '123456',
                        },
                    }
```
The notification is received when app is in background.. When I tap on it, the app opens and then crashes with no error logs.
Simply Lost connection to device.

This is my onMessageOpenedApp function

```
onMessage = FirebaseMessaging.onMessageOpenedApp
        .listen((RemoteMessage message) async {
      var data = message.data ?? ((message as Map).cast<String, dynamic>());
      if (data['type'] == 'inbox') {
        await goToInbox();
      }
      if (data['type'] == 'qna') {
        await goToQna(data);
      }
    });
```
I have tried removing the '((message as Map).cast<String, dynamic>());' before, but it didn't fix it.

When I try to print message, I get **flutter: Instance of 'RemoteMessage'**
This suggests that my message is being received and the function works, just that I suspect data field is null

### Steps to reproduce

1. Send a notification with data message to iOS device.
2. Tap on notification to open the app when app is killed or backgrounded.

### Expected behavior
1. App should open and navigate to the correct route.

---

## Additional context

The code in its old form works when using 7.0.3. I suspect iOS is not handling the data message correctly as previously it was not attached to the 'data' field; the data fields were simply appended to the message directly.. Now there seems to be no way to access those fields as RemoteMessage class hides those fields.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale en-SG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.50.1)
[✓] Connected device (3 available)
```
</details>

### LINKED ISSUE #4034: firebase_messaging 8.0.0-dev.5 breaks flutter_local_notifications
When using package firebase_messaging 8.0.0-dev.5 to test onBackgrounNotification the app becomes unresponsive when launching a local notification.

### PR DESCRIPTION
**Pull request by Salakar**
## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change.*

## Related Issues

 - Fixes #4026
 - Fixes #4034 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (please indicate a breaking change in CHANGELOG.md and increment major revision).
- [ ] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m [hunk 1]
```diff
@@ -219,24 +219,44 @@ - (void)application_onDidFinishLaunchingNotification:(nonnull NSNotification *)n
...
-              respondsToSelector:@selector(userNotificationCenter:
-                                          willPresentNotification:withCompletionHandler:)];
-      _originalNotificationCenterDelegateRespondsTo.didReceiveNotificationResponse =
-          (unsigned int)[_originalNotificationCenterDelegate
-              respondsToSelector:@selector(userNotificationCenter:
-                                     didReceiveNotificationResponse:withCompletionHandler:)];
+#if !TARGET_OS_OSX
+      // If there's an existing delegate and it is a FlutterApplicationLifeCycleDelegate then we
+      // don't want to replace it on iOS as the earlier call to `[_registrar
+      // addApplicationDelegate:self];` will automatically delgate calls to this plugin. If we
```
Comment (Salakar) [inline packages/firebase_messaging/firebase_messaging/ios/Classes/FLTFirebaseMessagingPlugin.m:230]:
```suggestion
      // addApplicationDelegate:self];` will automatically delegate calls to this plugin. If we
```
