### PR TITLE
fix(web, firestore): stop overwriting user errors

### LINKED ISSUE #5316: 🐛 [firebase_firestore] Exception during transaction propagates differently on Android and on web.
## Bug report

Error propagation is different if you build the app for Android or for web. The try block in the following code catches MyError on Android and FirebaseException on web. The code is 'unknown' and the message is 'MyException' in the second case.

### Steps to reproduce

```
class MyException implements Exception {
  const MyException();
  String toString() => 'MyException';
}
Future<void> fun() async {
  await firestore.runTransaction((transaction) async {
    throw MyException();
  });
}
...
try {
  await fun();
}
on MyException catch(e) {
  print(e);
}
on FirebaseException catch(e) {
  print(e.code);
  print(e.message);
}
```

### Expected behavior

Exceptions should have to propagate to the caller in both cases, so MyError should be caught on web as well.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.804], locale hu-HU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code, 64-bit edition (version 1.54.1)
[√] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.1

dependencies:
- cloud_firestore 1.0.1 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter 
meta]
- cloud_functions 1.0.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]- cupertino_icons 1.0.2
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- fl_chart 0.20.1 [flutter path_drawing equatable pedantic]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_progress_hud 2.0.0 [flutter]
- flutter_spinkit 5.0.0 [flutter]
- fluttertoast 8.0.1-nullsafety.0 [flutter flutter_web_plugins]
- get 4.0.0-nullsafety.2 [flutter]
- intl 0.17.0 [clock path]
- page_view_indicators 2.0.0 [flutter]
- sprintf 6.0.0

dev dependencies:
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_native_splash 1.0.3 [yaml image xml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]        
- cloud_functions_platform_interface 5.0.0 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.1 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]        
- collection 1.15.0
- crypto 3.0.0 [collection typed_data]
- equatable 2.0.0 [collection meta]
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- image 3.0.1 [archive meta xml]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_drawing 0.5.0-nullsafety.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0-nullsafety.0 [vector_math meta]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- xml 5.0.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

The current web implementation overwrites errors from Dart. This will propagate non-web platform errors as they are.

If this is an acceptable implementation, I'll also roll out for `firebase_auth` `firebase_messaging` & `firebase_storage` packages which have similar implementations.

## Related Issues

fixes #5316

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart [hunk 1]
```diff
@@ -57,7 +57,7 @@ class FirebaseFirestoreWeb extends FirebaseFirestorePlatform {
     try {
       await _webFirestore.clearPersistence();
     } catch (e) {
-      throw getFirebaseException(e);
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:60]: Considering how common this pattern is, it'd probably be worth to change it to:

```dart
Future<void> clearPersistence() async {
  return guard(() async {
    await _webFirestore.clearPersistence();
  });
}

R guard<R>(R Function() cb) {
  try {
    return cb();
  } catch (err, stack) {
    if (object is! core_interop.FirebaseError && object is Exception)
      rethrow;
    
    throw FirebaseException(...);
  }
}
```

File: packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart [hunk 2]
```diff
@@ -7,13 +7,13 @@ import 'package:firebase_core_web/firebase_core_web_interop.dart'
     as core_interop;
 
 /// Returns a [FirebaseException] from a thrown web error.
-FirebaseException getFirebaseException(Object object) {
-  if (object is! core_interop.FirebaseError) {
-    return FirebaseException(
-        plugin: 'cloud_firestore', message: object.toString());
+Exception getException(Object object) {
+  if (object is! core_interop.FirebaseError && object is Exception) {
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart:11]: What is the `is Exception` doing?

Comment (rrousselGit) [reply packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart:11]: Wouldn't we get a cast error if an `Error` is thrown instead?

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart (hunk 1 above)
Comment (rrousselGit) [reply packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:60]: The `rethrow` is pretty important here too imo

Because if the goal is to support user exceptions, we want to preserve the stacktrace, or they'd have an hard time figuring out what the issue is.

Comment (russellwheatley) [reply packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:60]: That is way better, didn't realise the stacktrace would be lost 👍

File: packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart (hunk 2 above)
Comment (russellwheatley) [reply packages/cloud_firestore/cloud_firestore_web/lib/src/utils/exception.dart:11]: Can get rid of `is Exception`, I just wanted it to be a bit more explicit that `Object` was an `Exception`. But I guess it will be a problem if it is an `Error`. Will remove.

**Comment by Salakar** [comment]
We do this try catch stuff in every FlutterFire package, should we perhaps move guard/guardSync to `firebase_core` and slowly refactor everywhere else we're doing this try catch wrapping on Firebase SDK calls (in another PR of course) - thoughts @russellwheatley @rrousselGit?

**Comment by rrousselGit** [comment]
Agreed

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart [hunk 3]
```diff
@@ -54,11 +53,7 @@ class FirebaseFirestoreWeb extends FirebaseFirestorePlatform {
 
   @override
   Future<void> clearPersistence() async {
-    try {
-      await _webFirestore.clearPersistence();
-    } catch (e) {
-      throw getFirebaseException(e);
-    }
+    return guard(_webFirestore.clearPersistence);
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:56]: In those cases, you can remove the `async` keyword from the function

It's a slight performance boost.

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart [hunk 4]
```diff
@@ -98,17 +85,14 @@ class FirebaseFirestoreWeb extends FirebaseFirestorePlatform {
...
-        return transactionHandler(
-            TransactionWeb(this, _webFirestore, transaction!));
-      }).timeout(timeout);
-      // Workaround for 'Runtime type information not available for type_variable_local'
-      // See: https://github.com/dart-lang/sdk/issues/29722
-      return null;
-    } catch (e) {
-      throw getFirebaseException(e);
-    }
+    await guard(() => _webFirestore.runTransaction((transaction) async {
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:88]: This function looks broken. It appears that it now _always_ return `null`

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart [hunk 5]
```diff
@@ -125,43 +109,29 @@ class FirebaseFirestoreWeb extends FirebaseFirestorePlatform {
     }
 
     if (settings.host != null && settings.sslEnabled != null) {
-      _webFirestore.settings(firestore_interop.Settings(
+      guardSync(() => _webFirestore.settings(firestore_interop.Settings(
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:112]: `settings` apparently did not throw a FirebaseException before. Is this a voluntary behavior change?

File: packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart [hunk 6]
```diff
@@ -27,44 +26,29 @@ class DocumentReferenceWeb extends DocumentReferencePlatform {
...
   Future<void> set(Map<String, dynamic> data, [SetOptions? options]) async {
-    try {
-      await _delegate.set(
-        CodecUtility.encodeMapData(data)!,
-        convertSetOptions(options),
-      );
-    } catch (e) {
-      throw getFirebaseException(e);
-    }
+    return guard(() => _delegate.set(
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/src/document_reference_web.dart:29]: nit: In general, I would not use `=>` unless the content can be expressed in a single line.
So here I'd use `{}`

File: packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart [hunk 7]
```diff
@@ -123,3 +126,51 @@ firestore_interop.SetOptions? convertSetOptions(SetOptions? options) {
...
 }
+
+FirebaseException buildFirebaseException(
+    core_interop.FirebaseError firebaseError) {
+  String code = firebaseError.code.replaceFirst('firestore/', '');
+  String message =
+      firebaseError.message.replaceFirst('(${firebaseError.code})', '');
+  return FirebaseException(
+      plugin: 'cloud_firestore', code: code, message: message);
+}
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart:137]:
```suggestion
FirebaseException buildFirebaseException(
    core_interop.FirebaseError firebaseError,
) {
  String code = firebaseError.code.replaceFirst('firestore/', '');
  String message =
      firebaseError.message.replaceFirst('(${firebaseError.code})', '');

    return FirebaseException(
      plugin: 'cloud_firestore',
      code: code,
      message: message,
    );
}
```

File: packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart [hunk 8]
```diff
@@ -123,3 +126,51 @@ firestore_interop.SetOptions? convertSetOptions(SetOptions? options) {
...
+    if (error is! core_interop.FirebaseError) {
+      rethrow;
+    }
+
+    throw buildFirebaseException(error);
+  }
+}
+
+/// Returns a [FirebaseException] from a thrown web error.
+Exception getFirebaseException(Object object) {
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart:170]: Is this still used?

File: packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart [hunk 9]
```diff
@@ -123,3 +126,51 @@ firestore_interop.SetOptions? convertSetOptions(SetOptions? options) {
...
+  if (object is! core_interop.FirebaseError && object is Exception) {
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart:171]: I'd reverse the condition:

```dart
if (object is core_interop.FirebaseError) {
  return buildFirebaseException(object);
}

return object;
```

and make the function return an `Object`.

File: packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart (hunk 8 above)
Comment (russellwheatley) [reply packages/cloud_firestore/cloud_firestore_web/lib/src/utils/web_utils.dart:175]: Yeah, it is still used. I wasn't sure how to capture the error in error handlers like this one: https://github.com/FirebaseExtended/flutterfire/blob/@russell/firestore-web-exception/packages/cloud_firestore/cloud_firestore_web/lib/src/query_web.dart#L158

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart (hunk 4 above)
Comment (rrousselGit) [reply packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart]: Oh my bad. But then I don't get why this function returns `T`, if it justs never return anything

File: packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart (hunk 3 above)
Comment (rrousselGit) [reply packages/cloud_firestore/cloud_firestore_web/lib/cloud_firestore_web.dart:56]: @russellwheatley This needs to be applied to all the modified functions, not just this one

Like disableNettwork/enableNetwork/...

**Review by rrousselGit — APPROVED** [review]
LGTM with a minor nit

**Review by rrousselGit — APPROVED** [review]

**Comment by rrousselGit** [comment]
Looks good to go (I believe the failing test just need a re-run)
