### PR TITLE
fix(functions): return correct type on native

### LINKED ISSUE #4059: 🐛 [cloud_functions] Result's type from a Function returning json should be Map<String, dynamic>
## Bug report

Hi, if I return json from a Cloud Function, in this case a list of objects, the `data` property itself has a type of `List<dynamic>`, which is correct, however, the objects in there don't have a type of `Map<String, dynamic>` as you'd expect with json in Dart, but a type of `_InternalLinkedHashMap<dynamic, dynamic>`. The problem here is the `<dynamic, dynamic>`, the keys should be guaranteed to be `String`s. Now for example, the `json_serializable` package doesn't work without rebuilding the json with the proper types.

### Steps to reproduce

1. Create a Cloud Function that returns json
2. See that result type on the Dart side is incorrect

### Expected behavior

In my case, the type should be `List<dynamic>`, however the objects themselves should be `Map<String, dynamic>`.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.24.0-4.0.pre.55, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2020.2)
[✓] VS Code (version 1.50.1)
[✓] Connected device (4 available)

! Doctor found issues in 1 category.
```

</details>

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

If a cloud function returns an object, the return type ought to be `Map<String, dynamic>`, not `Map<dynamic, dynamic>` as per JSON spec. This problem affects `iOS` & `android`, `web` returns the correct type.

## Related Issues

fixes #4059

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart [hunk 1]
```diff
@@ -27,5 +27,11 @@ class MethodChannelHttpsCallable extends HttpsCallablePlatform {
       'timeout': options.timeout.inMilliseconds,
       'parameters': parameters,
     }).catchError(catchPlatformException);
+
+    if (result is Map) {
```
Comment (rrousselGit) [inline packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart:31]: Would it be difficult to test?

File: packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart [hunk 2]
```diff
@@ -17,8 +17,8 @@ class MethodChannelHttpsCallable extends HttpsCallablePlatform {
       : super(functions, origin, name, options);
 
   @override
-  Future<dynamic> call([dynamic parameters]) {
-    return MethodChannelFirebaseFunctions.channel
+  Future<dynamic> call([dynamic parameters]) async {
+    dynamic result = await MethodChannelFirebaseFunctions.channel
```
Comment (rrousselGit) [inline packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart:21]:
```suggestion
    Object? result = await MethodChannelFirebaseFunctions.channel
```

Comment (rrousselGit) [inline packages/cloud_functions/cloud_functions_platform_interface/lib/src/method_channel/method_channel_https_callable.dart:21]:
```suggestion
  Future<Object?> call([Object? parameters]) async {
    Object? result = await MethodChannelFirebaseFunctions.channel
```

**Review by rrousselGit — APPROVED** [review]
