### PR TITLE
fix(firestore): made `QueryDocumentSnapshot.data()` non-nullable

### LINKED ISSUE #5475: 🐛 [cloud_firestore] QueryDocumentSnapshot.data should be non-null
## Bug report

Currently, `QueryDocumentSnapshot` inherits its `.data()` from `DocumentSnapshot`, which is nullable. However, the [docs](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/QueryDocumentSnapshot-class.html) ensure that it will never be null: 
> A QueryDocumentSnapshot offers the same API surface as a DocumentSnapshot. Since query results contain only existing documents, the exists property will always be true and data() will never return null.

### Expected behavior

`QueryDocumentSnapshot` should override its `.data()` method and replace the return type with the (non-nullable) `Map<String, dynamic>`.

## Additional context

I opened a PR (#5476) to fix this.

---
```YAML
cloud_firestore: 1.0.2
```

### PR DESCRIPTION
**Pull request by Levi-Lesches**
QueryDocumentSnapshot, by definition, should always have data and therefore the `.data()` method can be non-null.

## Description

Adds an override that calls the super `.data()` method with the added `!`.

## Related Issues

FIxes #5475 

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
  **There was no existing test for `Query.get()`, but the change is just from nullable to non-nullable.**
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`). **Docs already had the correct info**
- [x] The analyzer (`flutter analyze`) does not report any problems on my PR.
- [x] I read and followed the [Flutter Style Guide].
- [x] I signed the [CLA].
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart [hunk 1]
```diff
@@ -16,4 +16,7 @@ class QueryDocumentSnapshot extends DocumentSnapshot {
 
   @override
   bool get exists => true;
+
```
Comment (Levi-Lesches) [inline packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart:19]:
```suggestion

```

**Comment by Levi-Lesches** [comment]
No clue why the web test is failing. It's a test for Collection.snapshots(), but I don't think it's because of my code, especially since  making a type null safe should only bring about static errors, if any, whereas these were runtime. Note that the Android and iOS tests passed. 

Here's the error:
> ```
> ✘ listens to a multiple changes response
>   [E]: Expected: <2>
>   Action: <3>
>     [LOG]: 00:17 +52 ~9 -1: Query Query.snapshots() listeners throws a [FirebaseException]
>     [LOG]: 00:18 +52 ~9 -1: Query Query.snapshots() listens to a multiple changes response [E]
>     [LOG]:   Callback called more times than expected (5).
>   Stream should only have been called five times.
> ``` 

Here's the test in question: 
https://github.com/FirebaseExtended/flutterfire/blob/b77c683a103fc02acaf89440002cc9b9a13b3ea8/packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart#L152-L199

**Review by Salakar — APPROVED** [review]

**Comment by Salakar** [comment]
Re-ran CI as I imagine this is just a flake.

File: packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart [hunk 2]
```diff
@@ -16,4 +16,6 @@ class QueryDocumentSnapshot extends DocumentSnapshot {
 
   @override
   bool get exists => true;
+  @override
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore/lib/src/query_document_snapshot.dart:19]:
```suggestion

  @override
```

**Review by rrousselGit — APPROVED** [review]
LGTM

**Comment by rrousselGit** [comment]
I'm surprised that this change does not require the removal of any `!` in the project.
We don't have tests for this? 🤔

**Comment by Levi-Lesches** [comment]
@rrousselGit, by perusing the [`cloud_firestore`](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/cloud_firestore) directory, I found only two cases that would need `!`, but neither of them have it because they both explicitly disable nnbd by including `// @dart=2.9`:

- [`example/lib/main.dart`](https://github.com/FirebaseExtended/flutterfire/blob/942cfb58a44f9572ee41758f6cff656491c325e2/packages/cloud_firestore/cloud_firestore/example/lib/main.dart) -- The example `Movie` widget refers to `DocumentSnapshot`, not `QueryDocumentSnapshot` (although that could be changed).
- [`example/test_driver/query_e2e.dart`](https://github.com/FirebaseExtended/flutterfire/blob/942cfb58a44f9572ee41758f6cff656491c325e2/packages/cloud_firestore/cloud_firestore/example/test_driver/query_e2e.dart) -- all variables named `documentSnapshot` are `QueryDocumentSnapshot`s.
