### PR TITLE
fix(firestore): improve query filter assertions

### LINKED ISSUE #6548: 🐛 [cloud_firestore] No more able to query a document by its ID and another field without exception
## Bug report

**Describe the bug**

As described at the end of [this StackOverflow question](https://stackoverflow.com/questions/67556515/firestore-rules-to-allow-query-on-the-document-id-and-another-field), I am using this query:

```dart
await FirebaseFirestore.instance
    .collection('users')
    .where(FieldPath.documentId, isNotEqualTo: 'FAKE_ID')
    .where(FieldPath.documentId, isEqualTo: 'USER_ID')
    .where('deletionDate', isNull: true)
    .limit(1)
    .get()
```

To either receive the user document or no document if the user does not exist or has a deletion date set. In any situation, this does not trigger an error. So my Firestore rule monitoring only contains problems I should check without any false positive.

However since https://github.com/FirebaseExtended/flutterfire/pull/6225, this solution is no more working. I think there is no other way than getting the document by its ID. Catching and ignoring the exception on the Flutter app if the Firestore rule prevent the access. And not trust anymore the Firestore rules monitoring tool.

### Steps to reproduce

Create a Firestore rule for the `users` collection:

```
/users/{userId} {
  allow read: if resource.data.deletionDate == null;
}
```

Insert a document `/users/USER_ID` with `deletionDate` set to `2021-07-06T10:00:00Z`.

Then try to query it with the snippet provided at the beginning for this issue.

### Expected behavior

You should retrieve an empty `QuerySnapshot`.

## Additional context

Without `isNotEqualTo: 'FAKE_ID'`, Firestore behaves as if the document was accessed directly by its ID - instead of querying the collection on multiple fields. So it does trigger the access error due to `deletionDate`.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.6, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.6
app 1.0.0+1

dependencies:
- azlistview 2.0.0-nullsafety.0 [flutter scrollable_positioned_list]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 2.3.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 2.0.0 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- contacts_service 0.6.1 [flutter collection quiver]
- diacritic 0.1.3
- firebase_analytics 8.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 2.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.0.7 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_dynamic_links 2.0.6 [firebase_core flutter]
- firebase_messaging 10.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 9.0.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_google_places 0.3.0 [flutter google_api_headers google_maps_webservice http rxdart]
- flutter_image_compress 1.0.0 [flutter]
- flutter_secure_storage 4.2.0 [meta flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- google_maps_webservice 0.0.20-nullsafety.5 [http meta json_annotation]
- google_mobile_ads 0.13.2 [meta flutter]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- image_picker 0.8.1+3 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- maps_launcher 2.0.0 [flutter flutter_web_plugins url_launcher]
- permission_handler 8.1.2 [flutter meta permission_handler_platform_interface]
- provider 5.0.0 [collection flutter nested]
- share 2.0.4 [meta mime flutter]
- timeago 3.1.0
- url_launcher 6.0.8 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.4 [crypto]

dev dependencies:
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.2.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.2.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.7 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.9 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 5.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 2.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.6 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 3.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 2.0.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_api_headers 1.1.0 [flutter package_info_plus]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- js 0.6.3
- json_annotation 4.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_info_plus 1.0.3 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- package_info_plus_linux 1.0.2 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.1.1 [flutter]
- package_info_plus_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.2 [http package_info_plus_platform_interface flutter flutter_web_plugins meta]
- package_info_plus_windows 1.0.2 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.6.0 [flutter meta plugin_platform_interface]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- scrollable_positioned_list 0.2.0-nullsafety.0 [flutter collection]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

### PR DESCRIPTION
**Pull request by russellwheatley**
## Description

Fix where filter query assertion.

## Related Issues

fixes #6548

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`).
This will ensure a smooth and quick review process. Updating the `pubspec.yaml` and changelogs is not required.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] My PR includes unit or integration tests for *all* changed/updated/fixed behaviors (See [Contributor Guide]).
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] The analyzer (`melos run analyze`) does not report any problems on my PR.
- [ ] I read and followed the [Flutter Style Guide].
- [ ] I signed the [CLA].
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require plugin users to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change.
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/FirebaseExtended/flutterfire/blob/master/CONTRIBUTING.md
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[CLA]: https://cla.developers.google.com/

### CODE REVIEW

File: packages/cloud_firestore/cloud_firestore/lib/src/query.dart [hunk 1]
```diff
@@ -678,10 +679,19 @@ class _JsonQuery implements Query<Map<String, dynamic>> {
...
+              ' filters whilst using a FieldPath.documentId field in another filter.',
+        );
+      }
+
       if (field == FieldPath.documentId) {
         assert(
-          !hasNotEqualTo,
-          "You cannot use '!=' filters with a FieldPath.documentId field.",
+          !hasNotEqualToNotOperatorAndNotDocumentIdField,
+          'You cannot use FieldPath.documentId field whilst using a ' !=
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore/lib/src/query.dart:693]: There's an issue with quotes I think. This will print "false" instead of the message

File: packages/cloud_firestore/cloud_firestore/lib/src/query.dart [hunk 2]
```diff
@@ -678,10 +679,19 @@ class _JsonQuery implements Query<Map<String, dynamic>> {
         );
       }
 
+      if (field != FieldPath.documentId && hasDocumentIdField) {
+        assert(
+          operator != '!=',
+          'You cannot use ' !=
+              ' filters whilst using a FieldPath.documentId field in another filter.',
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore/lib/src/query.dart:686]: Same here

File: packages/cloud_firestore/cloud_firestore/lib/src/query.dart [hunk 3]
```diff
@@ -656,6 +656,7 @@ class _JsonQuery implements Query<Map<String, dynamic>> {
     bool hasIn = false;
     bool hasNotIn = false;
     bool hasNotEqualTo = false;
+    bool hasNotEqualToNotOperatorAndNotDocumentIdField = false;
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore/lib/src/query.dart:659]: What a name haha

File: packages/cloud_firestore/cloud_firestore/test/query_test.dart [hunk 4]
```diff
@@ -202,6 +202,15 @@ void main() {
         );
       });
 
+      test(
+          'allow isNotEqualTo filter on FieldPath.documentId field & a different field on a separate filter',
+          () {
+        query!
+            .where(FieldPath.documentId, isNotEqualTo: 'fake-id')
+            .where(FieldPath.documentId, isEqualTo: 'another-fake-id')
+            .where('foo', isNull: true);
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore/test/query_test.dart:211]: The isNull case probably should be a separate test

File: packages/cloud_firestore/cloud_firestore/lib/src/query.dart (hunk 3 above)
Comment (russellwheatley) [reply packages/cloud_firestore/cloud_firestore/lib/src/query.dart:659]: ha, I think there's an extra `Not` in there 😄. It should be `hasNotEqualToOperatorAndNotDocumentIdField`. Still not great, but I need to capture this use case.

File: packages/cloud_firestore/cloud_firestore/test/query_test.dart (hunk 4 above)
Comment (russellwheatley) [reply packages/cloud_firestore/cloud_firestore/test/query_test.dart:211]: No, this test proves the logic works. We're trying to fix an issue with this query:
```dart
await FirebaseFirestore.instance
    .collection('users')
    .where(FieldPath.documentId, isNotEqualTo: 'FAKE_ID')
    .where(FieldPath.documentId, isEqualTo: 'USER_ID')
    .where('deletionDate', isNull: true)
    .limit(1)
    .get()
```

It's the combination of queries that matters, not in isolation.

Comment (rrousselGit) [reply packages/cloud_firestore/cloud_firestore/test/query_test.dart:211]: I see, alright then

File: packages/cloud_firestore/cloud_firestore/lib/src/query.dart [hunk 5]
```diff
@@ -715,9 +723,12 @@ class _JsonQuery implements Query<Map<String, dynamic>> {
       if (operator == '!=') {
         assert(!hasNotEqualTo, "You cannot use '!=' filters more than once.");
         assert(!hasNotIn, "You cannot use '!=' filters with 'not-in' filters.");
-        assert(!hasDocumentIdField,
-            "You cannot use a FieldPath.documentId field with '!=' filters.");
+
         hasNotEqualTo = true;
+
+        if (field != FieldPath.documentId) {
+          hasNotEqualToOperatorAndNotDocumentIdField = true;
```
Comment (rrousselGit) [inline packages/cloud_firestore/cloud_firestore/lib/src/query.dart:730]: What is the purpose of this assignment? From this point, the variable is not used anymore

Comment (rrousselGit) [reply packages/cloud_firestore/cloud_firestore/lib/src/query.dart:730]: Wait ignore me, there's an hidden `for` loop

**Review by rrousselGit — APPROVED** [review]
